# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20170311_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='divisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Divisa'),
        ),
        migrations.AlterField(
            model_name='tazacambio',
            name='divisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Divisa'),
        ),
    ]
